
const Q=[
{q:"Latitude is the angular distance of a place measured in degrees from:",opts:["Prime Meridian","The Equator (0 degrees)","The North Pole","The International Date Line"],ans:1,exp:"Latitude is measured in degrees north or south of the Equator (0 degrees). It ranges from 0 degrees at the Equator to 90 degrees N at the North Pole and 90 degrees S at the South Pole. Lines of latitude are also called Parallels as they run parallel to the Equator.",sec:"Latitude Basics"},
{q:"Lines of latitude are also called:",opts:["Meridians","Great Circles","Parallels","Isotherms"],ans:2,exp:"Lines of latitude are called Parallels because they run parallel to each other and to the Equator. They never meet each other. They run in the east-west direction but measure distance north or south. The distance between two consecutive parallels is approximately 111 km.",sec:"Latitude Basics"},
{q:"The Equator divides the Earth into:",opts:["Eastern and Western Hemispheres","Northern and Southern Hemispheres","Asia and Europe","Land and Water hemispheres"],ans:1,exp:"The Equator (0 degrees latitude) divides the Earth into the Northern Hemisphere (above the Equator) and the Southern Hemisphere (below the Equator). The Prime Meridian (0 degrees longitude) divides the Earth into the Eastern and Western Hemispheres.",sec:"Latitude Basics"},
{q:"The total number of latitudes including the Equator, the two poles and all parallels is:",opts:["90","180","181","360"],ans:2,exp:"Latitudes range from 0 degrees (Equator) to 90 degrees N (North Pole) and 90 degrees S (South Pole). Total = 90 north + 90 south + 1 (Equator) = 181. The Equator is counted once, giving 181 lines in total.",sec:"Latitude Basics"},
{q:"The Tropic of Cancer is located at:",opts:["23.5 degrees S","66.5 degrees N","23.5 degrees N","66.5 degrees S"],ans:2,exp:"The Tropic of Cancer is at 23.5 degrees N latitude. The Sun is directly overhead here on June 21 (Summer Solstice). It is the most northerly latitude where the Sun can appear directly overhead at solar noon.",sec:"Latitude Basics"},
{q:"The Tropic of Capricorn is located at:",opts:["23.5 degrees N","66.5 degrees N","66.5 degrees S","23.5 degrees S"],ans:3,exp:"The Tropic of Capricorn is at 23.5 degrees S latitude. The Sun is directly overhead here on December 22 (Winter Solstice for Northern Hemisphere / Summer Solstice for Southern Hemisphere).",sec:"Latitude Basics"},
{q:"The Arctic Circle is located at:",opts:["23.5 degrees N","45 degrees N","66.5 degrees N","90 degrees N"],ans:2,exp:"The Arctic Circle is at approximately 66.5 degrees N. Above this latitude, there is at least one day of continuous daylight (midnight sun) in summer and at least one day of continuous darkness (polar night) in winter.",sec:"Latitude Basics"},
{q:"The Antarctic Circle is located at:",opts:["23.5 degrees S","45 degrees S","66.5 degrees S","90 degrees S"],ans:2,exp:"The Antarctic Circle is at approximately 66.5 degrees S. It is the southern equivalent of the Arctic Circle. Below this latitude, midnight sun and polar night phenomena occur seasonally.",sec:"Latitude Basics"},
{q:"The distance between two consecutive parallels (latitudes) is approximately:",opts:["11 km","55 km","111 km","222 km"],ans:2,exp:"The distance between two consecutive parallels is approximately 111 km everywhere on Earth because parallels are equally spaced. This constant distance makes latitude a reliable measure of north-south distance. 1 minute of latitude = approximately 1.85 km (1 nautical mile).",sec:"Latitude Basics"},
{q:"Which of the following is the ONLY parallel that is also a Great Circle?",opts:["Tropic of Cancer","Arctic Circle","Tropic of Capricorn","Equator (0 degrees)"],ans:3,exp:"The Equator is the only parallel that is a Great Circle because its plane passes through the centre of the Earth, dividing it into two equal halves. All other parallels are smaller circles whose planes do not pass through Earth's centre. All meridians (lines of longitude) are Great Circles.",sec:"Latitude Basics"},
{q:"The total number of parallels between the Equator and each pole is:",opts:["45","89","90","91"],ans:2,exp:"Between the Equator (0 degrees) and each pole (90 degrees), there are 89 parallels (1 degree through 89 degrees). Including the Equator itself = 90 lines from Equator to Pole. Including both poles = 181 total latitudes on the entire globe.",sec:"Latitude Basics"},
{q:"The value of latitude at the North Pole is:",opts:["0 degrees","45 degrees N","66.5 degrees N","90 degrees N"],ans:3,exp:"The North Pole is at 90 degrees N latitude. The South Pole is at 90 degrees S. The Equator is 0 degrees. No latitude exists beyond 90 degrees N or S as those are the poles themselves — single points.",sec:"Latitude Basics"},
{q:"The Equator is at 0 degrees latitude. It passes through which continent in both South America and Africa?",opts:["It does not pass through South America","It passes through the northern part of South America (Ecuador, Colombia, Brazil) and through equatorial Africa","It passes only through Africa","It passes only through Asia and the Pacific Ocean"],ans:1,exp:"The Equator passes through: South America (Ecuador, Colombia, Brazil) and Africa (Gabon, Republic of Congo, DR Congo, Uganda, Kenya, Somalia). Ecuador is literally named after it. The Equator also passes through the Indian Ocean, Atlantic Ocean, and Pacific Ocean as well as Indonesia.",sec:"Latitude Basics"},
{q:"On which two dates is the Sun directly overhead at the Equator?",opts:["June 21 and December 22","January 1 and July 1","March 21 (Vernal Equinox) and September 23 (Autumnal Equinox)","April 1 and October 1"],ans:2,exp:"The Sun is directly overhead at the Equator on March 21 (Vernal/Spring Equinox) and September 23 (Autumnal Equinox). On these dates, day and night are approximately equal (12 hours each) everywhere on Earth. The word Equinox comes from Latin meaning equal night.",sec:"Latitude Basics"},
{q:"The five major parallels of latitude from north to south are in which correct order?",opts:["Arctic Circle, Tropic of Cancer, Equator, Tropic of Capricorn, Antarctic Circle","Equator, Tropic of Cancer, Tropic of Capricorn, Arctic Circle, Antarctic Circle","Arctic Circle, Equator, Tropic of Cancer, Tropic of Capricorn, Antarctic Circle","Tropic of Cancer, Arctic Circle, Equator, Antarctic Circle, Tropic of Capricorn"],ans:0,exp:"Correct order from North to South: (1) Arctic Circle (66.5 N), (2) Tropic of Cancer (23.5 N), (3) Equator (0 degrees), (4) Tropic of Capricorn (23.5 S), (5) Antarctic Circle (66.5 S). These five major parallels divide the Earth into different heat zones.",sec:"Latitude Basics"},
{q:"Longitude is the angular distance of a place measured in degrees from:",opts:["The Equator","The North Pole","The Prime Meridian (0 degrees longitude) — east or west","The Tropic of Cancer"],ans:2,exp:"Longitude is measured east or west of the Prime Meridian (0 degrees), which passes through Greenwich, London. Longitude ranges from 0 degrees to 180 degrees East and 0 degrees to 180 degrees West. Lines of longitude are called Meridians.",sec:"Longitude Basics"},
{q:"Lines of longitude are called:",opts:["Parallels","Isotherms","Meridians","Isobars"],ans:2,exp:"Lines of longitude are called Meridians. All meridians are semi-circles that run from the North Pole to the South Pole. They all have equal length, unlike parallels which decrease in circumference as you move toward the poles. All meridians are Great Circles.",sec:"Longitude Basics"},
{q:"The Prime Meridian (0 degrees) passes through:",opts:["Paris, France","New York, USA","Greenwich, London, United Kingdom","Cairo, Egypt"],ans:2,exp:"The Prime Meridian (0 degrees longitude) passes through the Royal Observatory at Greenwich, London, UK. It was established as the reference meridian in 1884 at the International Meridian Conference in Washington D.C. This meridian divides the Earth into Eastern and Western Hemispheres.",sec:"Longitude Basics"},
{q:"The total number of longitudes (meridians) is:",opts:["181","270","360","720"],ans:2,exp:"There are 360 longitudes in total: from 0 degrees (Prime Meridian) to 180 degrees East, and from 0 degrees to 180 degrees West, totaling 360 distinct lines. The 180 degrees East and 180 degrees West are the same line, approximately the International Date Line.",sec:"Longitude Basics"},
{q:"What is the maximum value of longitude?",opts:["90 degrees","180 degrees","270 degrees","360 degrees"],ans:1,exp:"The maximum value of longitude is 180 degrees, which can be East or West. The 180 degree meridian runs approximately through the Pacific Ocean and is roughly where the International Date Line is located. Longitudes range from 0 degrees to 180 degrees E and 0 degrees to 180 degrees W.",sec:"Longitude Basics"},
{q:"Unlike parallels, all meridians (lines of longitude) are equal in length. They converge at:",opts:["The Equator","The Tropic of Cancer and Tropic of Capricorn","Both the North and South Poles","The Prime Meridian"],ans:2,exp:"All meridians converge (meet) at both the North Pole (90 N) and South Pole (90 S). This is why time zones are wedge-shaped — wide at the equator and narrow at the poles. The distance between two meridians decreases as you move from the equator to the poles.",sec:"Longitude Basics"},
{q:"The distance between two consecutive meridians at the Equator is approximately:",opts:["10 km","55 km","111 km","200 km"],ans:2,exp:"At the Equator, the distance between two consecutive meridians (1 degree longitude) is approximately 111 km — the same as the distance between two consecutive parallels. This distance reduces as you move toward the poles, becoming zero at the poles themselves.",sec:"Longitude Basics"},
{q:"The Prime Meridian and International Date Line together divide the Earth into:",opts:["Four equal parts","Eastern and Western Hemispheres only","Eastern Hemisphere (0 to 180 E) and Western Hemisphere (0 to 180 W)","Northern and Southern Hemispheres"],ans:2,exp:"The Prime Meridian (0 degrees) and the 180 degrees meridian (approximate International Date Line) together divide the Earth into the Eastern Hemisphere (0 to 180 degrees E) and Western Hemisphere (0 to 180 degrees W). The Equator divides Earth into Northern and Southern Hemispheres.",sec:"Longitude Basics"},
{q:"All meridians are Great Circles because:",opts:["They are the longest lines on Earth","Their planes pass through the centre of the Earth, dividing it into two equal halves","They run east-west like the Equator","They are used for measuring distances"],ans:1,exp:"A Great Circle is any circle on Earth whose plane passes through the centre of the Earth. All meridians are Great Circles because each pair of opposite meridians (e.g., 0 and 180, 30E and 150W) forms a complete circle that passes through Earth's centre. The Equator is the only parallel that is a Great Circle.",sec:"Longitude Basics"},
{q:"The 180 degree meridian is significant because it approximately coincides with the:",opts:["Prime Meridian","Tropic of Cancer","International Date Line","Antarctic Circle"],ans:2,exp:"The 180 degree meridian approximately coincides with the International Date Line (IDL). The IDL deviates from the 180 degree line to avoid splitting countries and island groups. Crossing the IDL from east to west means gaining a day; crossing from west to east means losing a day.",sec:"Longitude Basics"},
{q:"Why is the Prime Meridian called the Prime Meridian?",opts:["Because it is the longest meridian","Because it passes through the capital city of England","It is the reference meridian (0 degrees) from which all other longitudes are measured — Prime means first or most important","Because it marks midnight"],ans:2,exp:"The Prime Meridian is the reference line (0 degrees longitude) established by international agreement in 1884. All longitudes are measured east or west of this line. It passes through the Royal Observatory, Greenwich, London. Before 1884, different countries used their own prime meridians.",sec:"Longitude Basics"},
{q:"Earth is divided into how many time zones based on longitude?",opts:["12","18","24","36"],ans:2,exp:"Earth is divided into 24 standard time zones because Earth rotates 360 degrees in 24 hours = 15 degrees per hour. Each time zone covers 15 degrees of longitude. Countries wider than 15 degrees have multiple time zones (Russia has 11, USA has 6). India uses a single time zone despite its wide longitudinal extent.",sec:"Longitude Basics"},
{q:"Earth rotates 360 degrees in 24 hours. Therefore it rotates how many degrees per hour?",opts:["10 degrees","12 degrees","15 degrees","20 degrees"],ans:2,exp:"Earth rotates 360 degrees in 24 hours: 360 / 24 = 15 degrees per hour. This is the basis of time zones. Every 15 degrees of longitude = 1 hour of time difference. Every 1 degree = 4 minutes of time difference. Memorise: 15 degrees = 1 hour, 1 degree = 4 minutes.",sec:"Longitude Basics"},
{q:"The time difference between two places 15 degrees apart in longitude is:",opts:["15 minutes","30 minutes","45 minutes","1 hour"],ans:3,exp:"Since Earth rotates 15 degrees per hour, two places 15 degrees apart in longitude have a time difference of exactly 1 hour. Places to the east have a later local time. Formula: Longitude difference / 15 = Time difference in hours. Example: India (82.5 E) is 82.5/15 = 5.5 hours ahead of Greenwich.",sec:"Longitude Basics"},
{q:"The time difference between two places 1 degree of longitude apart is:",opts:["1 minute","2 minutes","4 minutes","6 minutes"],ans:2,exp:"Earth rotates 15 degrees in 60 minutes, so it rotates 1 degree in 60/15 = 4 minutes. Therefore two places 1 degree of longitude apart have a time difference of 4 minutes. India spans about 29 degrees of longitude (97.25E - 68.7E), creating a local time difference of about 29 x 4 = 116 minutes (nearly 2 hours).",sec:"Longitude Basics"},
{q:"Places to the EAST of the Prime Meridian are:",opts:["Behind Greenwich time","Ahead of Greenwich time (add hours to GMT)","At the same time as Greenwich","Sometimes ahead, sometimes behind"],ans:1,exp:"Places east of the Prime Meridian (0 degrees) are AHEAD in time — they add hours to Greenwich Mean Time (GMT). Places west are BEHIND (subtract from GMT). India at 82.5 E is 5 hours 30 minutes AHEAD of GMT (IST = GMT + 5:30). New York at 75 W is 5 hours BEHIND GMT.",sec:"Longitude Basics"},
{q:"The International Date Line (IDL) approximately follows which meridian?",opts:["0 degrees (Prime Meridian)","90 degrees East","90 degrees West","180 degrees (with deviations to avoid splitting countries)"],ans:3,exp:"The IDL approximately follows the 180 degree meridian through the middle of the Pacific Ocean. It deviates from 180 degrees to keep countries and island groups on one side. Crossing from west to east (Asia to America) you go back a day. Crossing east to west (America to Asia) you go forward a day.",sec:"Longitude Basics"},
{q:"The three HEAT ZONES of the Earth are:",opts:["Hot, Warm and Cold Zones","Tropical, Subtropical and Polar Zones","TORRID ZONE, TEMPERATE ZONE, and FRIGID (POLAR) ZONE","Equatorial, Monsoon and Desert Zones"],ans:2,exp:"The three heat zones based on latitude: (1) TORRID ZONE: between Tropic of Cancer (23.5 N) and Tropic of Capricorn (23.5 S) — hottest, Sun overhead twice a year; (2) TEMPERATE ZONES: between Tropics and Polar Circles — moderate temperatures; (3) FRIGID ZONES: between Polar Circles and Poles — coldest. Each hemisphere has one Temperate and one Frigid zone.",sec:"Heat Zones"},
{q:"The Torrid Zone lies between:",opts:["Equator and both Polar Circles","Arctic Circle and Antarctic Circle","Tropic of Cancer (23.5 N) and Tropic of Capricorn (23.5 S)","45 degrees N and 45 degrees S"],ans:2,exp:"The Torrid Zone (from Latin Torridus = parched/very hot) lies between the Tropic of Cancer (23.5 N) and Tropic of Capricorn (23.5 S). It covers about 40% of Earth's surface and receives the most direct solar radiation. The Sun is overhead somewhere in this zone every day of the year.",sec:"Heat Zones"},
{q:"The North Temperate Zone lies between:",opts:["Equator and Tropic of Cancer","Tropic of Cancer (23.5 N) and Arctic Circle (66.5 N)","Arctic Circle and North Pole","Tropic of Capricorn and Antarctic Circle"],ans:1,exp:"The North Temperate Zone is between the Tropic of Cancer (23.5 N) and Arctic Circle (66.5 N). It has moderate temperatures with distinct four seasons. Most of India, Europe, China, USA, and Japan lie in this zone. The Sun never shines directly overhead here, but temperatures are not extreme.",sec:"Heat Zones"},
{q:"The North Frigid Zone lies between:",opts:["Equator and Arctic Circle","Tropic of Cancer and Arctic Circle","Arctic Circle (66.5 N) and North Pole (90 N)","Tropic of Cancer and North Pole"],ans:2,exp:"The North Frigid (Polar) Zone lies between the Arctic Circle (66.5 N) and the North Pole (90 N). It has extremely cold temperatures. The Sun never rises high in the sky. The zone experiences midnight sun (summer) and polar night (winter). The Arctic Ocean lies mainly within this zone.",sec:"Heat Zones"},
{q:"Which Heat Zone receives the maximum solar heat throughout the year?",opts:["North Temperate Zone","Frigid Zone","Torrid Zone — because the Sun shines vertically (overhead) here most of the year","South Temperate Zone"],ans:2,exp:"The Torrid Zone (between Tropics) receives maximum solar heat because the Sun's rays fall vertically (directly overhead) here throughout the year — either once or twice a year at specific dates. The Sun's vertical rays heat a smaller area more intensely than the slanted rays received at higher latitudes.",sec:"Heat Zones"},
{q:"The Sun is directly overhead at the Tropic of Cancer on:",opts:["December 22","March 21","September 23","June 21 (Summer Solstice)"],ans:3,exp:"The Sun is directly overhead at the Tropic of Cancer (23.5 N) on June 21, the Summer Solstice. This is the longest day of the year in the Northern Hemisphere. On December 22 (Winter Solstice), the Sun is overhead at the Tropic of Capricorn (23.5 S).",sec:"Heat Zones"},
{q:"The Sun is directly overhead at the Tropic of Capricorn on:",opts:["June 21","March 21","December 22 (Winter Solstice for Northern Hemisphere)","September 23"],ans:2,exp:"The Sun is directly overhead at the Tropic of Capricorn (23.5 S) on December 22, the Winter Solstice for the Northern Hemisphere. This is the shortest day in the Northern Hemisphere but the longest day in the Southern Hemisphere (their Summer Solstice).",sec:"Heat Zones"},
{q:"The midnight sun phenomenon occurs at latitudes:",opts:["Between the two Tropics","Between the Tropics and the Polar Circles","At and beyond the Arctic Circle (66.5 N) or Antarctic Circle (66.5 S) during their respective summers","Only at the poles"],ans:2,exp:"Midnight Sun (continuous daylight for 24+ hours) occurs at and above the Arctic Circle (66.5 N) during summer, and at and below the Antarctic Circle (66.5 S) during their summer. At the North Pole, this lasts for 6 months. At the Arctic Circle itself, there is just one day of midnight sun (around June 21).",sec:"Heat Zones"},
{q:"On equinox days (March 21 and September 23), day and night are equal because:",opts:["Earth is closest to the Sun","The Sun rises exactly in the north","The Sun is directly overhead the Equator, dividing the Earth equally into light and dark halves","There is no sunlight anywhere"],ans:2,exp:"On equinox days, the Sun is directly overhead the Equator (0 degrees). The circle of illumination passes exactly through both poles. This divides every latitude equally into 12 hours of day and 12 hours of night everywhere on Earth. The word Equinox comes from Latin: aequus (equal) + nox (night).",sec:"Heat Zones"},
{q:"The South Temperate Zone lies between:",opts:["Equator and Tropic of Capricorn","Tropic of Capricorn (23.5 S) and Antarctic Circle (66.5 S)","Antarctic Circle and South Pole","Tropic of Cancer and Tropic of Capricorn"],ans:1,exp:"The South Temperate Zone lies between the Tropic of Capricorn (23.5 S) and Antarctic Circle (66.5 S). It mirrors the North Temperate Zone. Countries like Australia (southern parts), Argentina, South Africa (southern parts), Chile, and New Zealand lie in this zone. It has moderate, pleasant temperatures.",sec:"Heat Zones"},
{q:"How many heat zones are there in the Earth in total?",opts:["3","4","5","6"],ans:2,exp:"There are 5 heat zones in total: (1) Torrid Zone (1 zone between the two Tropics), (2) North Temperate Zone, (3) South Temperate Zone, (4) North Frigid Zone, (5) South Frigid Zone. Total = 1 Torrid + 2 Temperate + 2 Frigid = 5 zones. Sometimes described as 3 types with 5 actual zones.",sec:"Heat Zones"},
{q:"India's Standard Time (IST) is ahead of Greenwich Mean Time (GMT) by:",opts:["5 hours","5 hours 30 minutes (UTC+5:30)","6 hours","5 hours 45 minutes"],ans:1,exp:"India Standard Time (IST) = GMT + 5 hours 30 minutes (UTC+5:30). This is because India's Standard Meridian is 82.5 degrees E. Calculation: 82.5 / 15 = 5.5 hours = 5 hours 30 minutes ahead of GMT. India has one single time zone for the entire country despite its wide longitudinal span.",sec:"Time and IST"},
{q:"India's Standard Meridian is 82 degrees 30 minutes E (82.5 E). It passes through which city in Uttar Pradesh?",opts:["Prayagraj (Allahabad)","Varanasi","Mirzapur","Lucknow"],ans:2,exp:"India's Standard Meridian (82 degrees 30 minutes East) passes through Mirzapur in Uttar Pradesh. This meridian was chosen because it is approximately in the middle of India's longitudinal extent (68.7 E to 97.25 E). The midpoint is around 82.9 E, making 82.5 E a practical choice.",sec:"Time and IST"},
{q:"If it is 12:00 noon at the Prime Meridian (0 degrees), what time is it in India (82.5 degrees E)?",opts:["6:30 AM","12:00 noon (same time)","5:30 PM","11:30 AM"],ans:2,exp:"India (82.5 E) is 82.5/15 = 5.5 hours = 5 hours 30 minutes ahead of Greenwich. So: 12:00 noon + 5 hours 30 minutes = 5:30 PM in India (IST). This is why when it is noon in London, it is already evening in India.",sec:"Time and IST"},
{q:"When it is 6:00 AM at Greenwich (0 degrees), what is the time in India?",opts:["12:30 AM","6:00 AM","11:30 AM","8:30 AM"],ans:2,exp:"India is 5 hours 30 minutes ahead of Greenwich. So 6:00 AM at Greenwich = 6:00 AM + 5:30 = 11:30 AM in India. To get IST from GMT: always add 5 hours and 30 minutes. To get GMT from IST: subtract 5 hours and 30 minutes.",sec:"Time and IST"},
{q:"India chose to have a SINGLE time zone despite spanning nearly 30 degrees of longitude. The main reason is:",opts:["India is too small to need multiple time zones","For administrative convenience — a single time zone avoids confusion in railways, airlines, banking, and governance across the country","International law requires large countries to have one time zone","The British established this rule during colonial times"],ans:1,exp:"India uses a single IST (UTC+5:30) for the entire country for administrative convenience: uniformity in railways, aviation, banks, and government offices. The downside is that in Gujarat (west), sunrise in winter can be after 7:30 AM, while in Arunachal Pradesh (east), sunrise can be before 5:30 AM — both using the same IST clock.",sec:"Time and IST"},
{q:"A city at 60 degrees West longitude would be how many hours BEHIND Greenwich?",opts:["2 hours","3 hours","4 hours","5 hours"],ans:2,exp:"60 degrees W / 15 = 4 hours behind Greenwich. West longitudes are behind GMT. So if it is 12:00 noon at Greenwich, it is 8:00 AM at 60 W. Example: Brazil (Brasilia at approximately 48 W) is about 3 hours behind GMT.",sec:"Time and IST"},
{q:"When crossing the International Date Line from WEST to EAST (e.g., from Japan to Hawaii):",opts:["You gain one day (calendar goes forward)","You lose one day (calendar goes back — subtract one day)","No change in date","You gain 12 hours"],ans:1,exp:"Crossing IDL from West to East (from Asia toward America) = LOSE one day (go back one day in the calendar). Crossing from East to West (from America toward Asia) = GAIN one day (go forward one day). This is why if you travel continuously westward around the globe, you gain a day by the time you return.",sec:"Time and IST"},
{q:"Nepal uses UTC+5:45 (5 hours 45 minutes ahead of GMT). This is because Nepal's central longitude is approximately:",opts:["80 degrees E","82.5 degrees E","84 degrees E","86 degrees E"],ans:2,exp:"Nepal's central longitude is approximately 84 degrees E (84/15 = 5.6 hours = 5 hours 36 minutes), which they rounded to 5 hours 45 minutes. Nepal uses UTC+5:45 — the world's most unusual 45-minute time offset. This places Nepal 15 minutes ahead of India (IST = UTC+5:30).",sec:"Time and IST"},
{q:"How many minutes ahead is IST compared to the local time at the eastern end of India (Arunachal Pradesh, approximately 97.25 E) compared to the western end (Gujarat, approximately 68.7 E)?",opts:["About 30 minutes","About 60 minutes","About 115 minutes (nearly 2 hours)","About 3 hours"],ans:2,exp:"India spans about 97.25 - 68.7 = 28.55 degrees of longitude. At 4 minutes per degree: 28.55 x 4 = about 114 minutes (nearly 2 hours). So sunrise in Arunachal Pradesh occurs about 2 hours before sunrise in Gujarat, despite both using the same IST clock time.",sec:"Time and IST"},
{q:"The Standard Time of a country is generally based on the longitude of:",opts:["Its eastern boundary","Its western boundary","The central meridian passing through the middle of the country","The Prime Meridian always"],ans:2,exp:"Standard Time of a country is based on a central meridian passing through or near the middle of the country. For India: 82.5 E (passes through Mirzapur, UP). For UK: 0 degrees (Prime Meridian). For USA: multiple standard meridians (75W, 90W, 105W, 120W, 150W) for its multiple time zones.",sec:"Time and IST"},
{q:"India's latitudinal extent (mainland India) from south to north is approximately:",opts:["8.4 N to 37.6 N","6.7 N to 37.6 N","8.4 N to 35.5 N","10 N to 40 N"],ans:0,exp:"India's mainland extends from approximately 8 degrees 4 minutes N (Kanyakumari, Tamil Nadu) to 37 degrees 6 minutes N (Ladakh region). Including the Andaman and Nicobar Islands, the southern extent is Indira Point in Great Nicobar at about 6 degrees 45 minutes N. The total north-south distance is about 3,214 km.",sec:"India Lat Long"},
{q:"India's longitudinal extent from west to east is approximately:",opts:["60.7 E to 97.25 E","68.7 E to 97.25 E","65 E to 95 E","70 E to 100 E"],ans:1,exp:"India extends from approximately 68 degrees 7 minutes E (western end in Gujarat/Rann of Kutch area) to 97 degrees 25 minutes E (eastern end in Arunachal Pradesh, near Kibithu). The east-west extent is about 2,933 km.",sec:"India Lat Long"},
{q:"The Tropic of Cancer passes through how many Indian states?",opts:["6 states","7 states","8 states","9 states"],ans:2,exp:"The Tropic of Cancer (23.5 N) passes through 8 Indian states: (1) Gujarat, (2) Rajasthan, (3) Madhya Pradesh, (4) Chhattisgarh, (5) Jharkhand, (6) West Bengal, (7) Tripura, (8) Mizoram. Memory trick: Gujarat Rajasthan MP CG JH WB Tripura Mizoram = 8 states.",sec:"India Lat Long"},
{q:"The southernmost point of mainland India is:",opts:["Indira Point (Great Nicobar)","Rameswaram (Tamil Nadu)","Kanyakumari (Cape Comorin, Tamil Nadu) at about 8 degrees 4 minutes N","Port Blair (Andaman Islands)"],ans:2,exp:"Kanyakumari (also called Cape Comorin) in Tamil Nadu, at approximately 8 degrees 4 minutes N, is the southernmost point of mainland India where the Arabian Sea, Bay of Bengal, and Indian Ocean meet. Indira Point in Great Nicobar Island (6 degrees 45 minutes N) is the absolute southernmost point including islands.",sec:"India Lat Long"},
{q:"The northernmost point of India is located in:",opts:["Jammu and Kashmir","Punjab","Himachal Pradesh","Ladakh (approximately 37 degrees 6 minutes N)"],ans:3,exp:"India's northernmost point is in the Ladakh region (Union Territory) at approximately 37 degrees 6 minutes N, in the Siachen area. Before Ladakh became a separate UT, it was in Jammu and Kashmir. This is the Indira Col area in the Karakoram ranges.",sec:"India Lat Long"},
{q:"The easternmost point of India is in which state?",opts:["Manipur","Nagaland","Assam","Arunachal Pradesh (approximately 97 degrees 25 minutes E)"],ans:3,exp:"India's easternmost point is in Arunachal Pradesh at approximately 97 degrees 25 minutes E, near Kibithu in Anjaw district. Arunachal Pradesh therefore receives sunrise about 2 hours earlier than Gujarat. The eastern states are sometimes called India's 'sunrise states'.",sec:"India Lat Long"},
{q:"The westernmost point of India is in which state?",opts:["Rajasthan","Punjab","Gujarat (approximately 68 degrees 7 minutes E)","Maharashtra"],ans:2,exp:"India's westernmost point is in Gujarat at approximately 68 degrees 7 minutes E, in the Rann of Kutch area (near Sir Creek/Guhar Moti). Gujarat has both the westernmost point and the longest coastline among Indian states (approximately 1,600 km).",sec:"India Lat Long"},
{q:"Which Indian city is located close to the Tropic of Cancer and is the city of the 'Pink City' or famous for its palaces?",opts:["Delhi (28.6 N)","Mumbai (18.9 N)","Kolkata (22.5 N) — very close to Tropic of Cancer (23.5 N)","Bengaluru (12.9 N)"],ans:2,exp:"Kolkata at approximately 22.5 N is the largest Indian city closest to the Tropic of Cancer (23.5 N) — just about 1 degree south of it. The Tropic of Cancer actually passes through parts of the greater Kolkata metropolitan area. This proximity gives Kolkata its hot, humid subtropical climate.",sec:"India Lat Long"},
{q:"India's Standard Meridian (82.5 E) was selected as the basis for IST because:",opts:["It passes through India's capital New Delhi","It passes through Mumbai, the financial capital","It is approximately the central longitude of India's east-west extent, providing a practical single time reference","The British established it as a colonial convenience"],ans:2,exp:"82.5 E was chosen as India's Standard Meridian because: (1) It is approximately the central longitude of India (between 68.7 E and 97.25 E, midpoint ≈ 82.9 E); (2) It gives a convenient IST of exactly UTC+5:30 (82.5/15 = 5.5 hours); (3) It passes through Mirzapur (UP), a central location. IST was officially adopted in 1906 for railway coordination.",sec:"India Lat Long"},
{q:"The Tropic of Cancer does NOT pass through which of these Indian states?",opts:["Madhya Pradesh","Chhattisgarh","Maharashtra","Jharkhand"],ans:2,exp:"The Tropic of Cancer passes through: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, Mizoram (8 states). It does NOT pass through Maharashtra. Maharashtra lies entirely south of the Tropic of Cancer (Maharashtra extends from about 15.6 N to 22.1 N — at most touching 22.1 N, not reaching 23.5 N).",sec:"India Lat Long"},
{q:"India lies entirely in which hemisphere(s)?",opts:["Southern Hemisphere only","Northern Hemisphere and Eastern Hemisphere both","Western Hemisphere and Northern Hemisphere","Southern Hemisphere and Eastern Hemisphere"],ans:1,exp:"India lies entirely in the NORTHERN HEMISPHERE (8 N to 37 N — all north of the Equator) and entirely in the EASTERN HEMISPHERE (68.7 E to 97.25 E — all east of the Prime Meridian). So India is in the northeast quadrant of the globe. This affects India's seasons, climate, and position on world maps.",sec:"India Lat Long"},
{q:"The Tropic of Cancer passes through which of the following Indian states CORRECTLY?",opts:["Gujarat, Maharashtra, MP, Jharkhand","Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, Mizoram","Rajasthan, UP, Bihar, West Bengal","Gujarat, Rajasthan, MP, UP, Bihar, West Bengal, Assam, Manipur"],ans:1,exp:"Correct list of 8 states through which Tropic of Cancer passes: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram. Note: UP, Bihar, Assam, Manipur are NOT in the list. Maharashtra is also not in the list.",sec:"India Lat Long"},
{q:"The latitudinal and longitudinal extent of India is approximately the same — about 30 degrees. This means:",opts:["India is a perfectly square-shaped country","India is circular in shape","India's north-south and east-west extents are approximately equal — roughly 3,000 km each — but the shape is not square; the local time difference between east and west is about 2 hours","India fits exactly between two time zones"],ans:2,exp:"India spans about 30 degrees of latitude (N-S) and about 30 degrees of longitude (E-W), making the distances roughly equal at about 3,000 km each. However, the shape is triangular (broader in the north, tapering south). The 30-degree longitude span creates about 2 hours of local time difference between Gujarat and Arunachal Pradesh.",sec:"India Lat Long"},
{q:"The geographic grid formed by the network of parallels (latitudes) and meridians (longitudes) is called:",opts:["Topographic map","The Graticule","Contour lines","Isoline map"],ans:1,exp:"The network of parallels and meridians drawn on a map or globe is called the Graticule. It forms a geographic grid that allows any location on Earth to be precisely identified using latitude and longitude coordinates. The graticule is the foundation of all geographic positioning systems including modern GPS.",sec:"Grid and Concepts"},
{q:"Using the geographic grid, the location of any place is given as:",opts:["Only latitude","Only longitude","BOTH latitude and longitude coordinates (e.g., New Delhi is approximately 28.6 N, 77.2 E)","Direction from the Prime Meridian only"],ans:2,exp:"Any place on Earth is uniquely identified by BOTH its latitude and longitude. Latitude tells you how far north or south of the Equator, and longitude tells you how far east or west of the Prime Meridian. Together they give an exact grid reference. New Delhi: 28.6 N, 77.2 E. Mumbai: 18.9 N, 72.8 E.",sec:"Grid and Concepts"},
{q:"The geographic coordinates (latitude and longitude) are measured in:",opts:["Metres and kilometres","Degrees, Minutes, and Seconds (e.g., 28 degrees 36 minutes 0 seconds N)","Radians only","Knots and nautical miles"],ans:1,exp:"Geographic coordinates use degrees, minutes, and seconds: 1 degree = 60 minutes; 1 minute = 60 seconds. Example: New Delhi is at 28 degrees 36 minutes N, 77 degrees 12 minutes E. In decimal form: 28.6 N, 77.2 E. Modern GPS systems often use decimal degrees for precision.",sec:"Grid and Concepts"},
{q:"The Great Circle route is the shortest path between two points on Earth. All meridians are Great Circles. Which is the ONLY parallel that is also a Great Circle?",opts:["Tropic of Cancer","Arctic Circle","Equator (0 degrees)","45 degrees N parallel"],ans:2,exp:"The Equator is the ONLY parallel that is a Great Circle because its plane passes through the centre of the Earth, dividing it into two perfectly equal halves. All other parallels (e.g., Tropic of Cancer, Arctic Circle) are small circles — their planes do not pass through Earth's centre. Airlines use Great Circle routes to fly the shortest distance between cities.",sec:"Grid and Concepts"},
{q:"Which of the following statements about parallels and meridians is CORRECT?",opts:["Parallels and meridians are both the same length","Parallels get shorter toward the poles; meridians are all equal in length","Meridians get shorter toward the equator; parallels are all equal length","Both parallels and meridians get shorter toward the poles"],ans:1,exp:"PARALLELS get shorter as you move from the Equator toward the poles — the Equator is the longest parallel (~40,075 km circumference), while the poles are just points. MERIDIANS are all equal in length — each meridian is a semi-circle from North Pole to South Pole of equal length (~20,004 km each).",sec:"Grid and Concepts"},
{q:"The latitude of a place can be determined using the altitude (angle) of the:",opts:["Moon","The nearest mountain peak","Pole Star (Polaris) above the horizon — its altitude above the horizon equals the latitude of the observer","The Sun at midnight"],ans:2,exp:"The altitude (angle above the horizon) of the Pole Star (Polaris) is equal to the latitude of the observer. At the North Pole (90 N), Polaris is directly overhead. At the Equator (0 degrees), Polaris is on the horizon (0 degrees altitude). This method has been used by sailors for centuries for navigation.",sec:"Grid and Concepts"},
{q:"The Pole Star (Dhruv Tara) is useful for determining latitude because:",opts:["It is the brightest star in the sky","It is exactly at the North Celestial Pole — its angle above the horizon equals the observer's latitude","It sets and rises at the same time as the Sun","It is directly above the Equator"],ans:1,exp:"Polaris (the Pole Star / North Star) is located almost exactly at the North Celestial Pole — it appears to not move in the sky while all other stars rotate around it. Its angle above the northern horizon equals the observer's latitude. This is why sailors used it for navigation for thousands of years.",sec:"Grid and Concepts"},
{q:"Which of these represents the ABSOLUTE LOCATION of a place?",opts:["New Delhi is the capital of India","New Delhi is north of Mumbai","New Delhi is at approximately 28.6 degrees N, 77.2 degrees E","New Delhi is in the Indo-Gangetic Plain"],ans:2,exp:"Absolute location is the exact position of a place on Earth given by specific latitude and longitude coordinates. New Delhi at 28.6 N, 77.2 E is its absolute location — unique to that spot on Earth. Relative location describes a place in relation to other places (e.g., north of Mumbai, in northern India).",sec:"Grid and Concepts"},
{q:"The 'Torrid Zone' is also called the:",opts:["Temperate Zone","Frigid Zone","Tropical Zone — the zone between the Tropics where the Sun is overhead","Polar Zone"],ans:2,exp:"The Torrid Zone is also called the Tropical Zone. It lies between the Tropic of Cancer (23.5 N) and Tropic of Capricorn (23.5 S). The word 'Torrid' means extremely hot. This zone receives maximum solar radiation and contains the world's tropical rainforests, hot deserts, and equatorial climates.",sec:"Grid and Concepts"},
{q:"The two Temperate Zones of Earth are between:",opts:["Equator and Polar Circles","Tropic of Cancer and Arctic Circle (in north) AND Tropic of Capricorn and Antarctic Circle (in south)","Polar Circles and Poles in both hemispheres","Equator and both Tropics"],ans:1,exp:"Two Temperate Zones: (1) NORTH TEMPERATE ZONE: between Tropic of Cancer (23.5 N) and Arctic Circle (66.5 N); (2) SOUTH TEMPERATE ZONE: between Tropic of Capricorn (23.5 S) and Antarctic Circle (66.5 S). These zones have moderate temperatures and four distinct seasons.",sec:"Grid and Concepts"},
{q:"Which heat zone do most parts of India fall in?",opts:["Frigid Zone","South Temperate Zone","TORRID ZONE and NORTH TEMPERATE ZONE both — because India extends from about 8 N to 37 N, with the Tropic of Cancer (23.5 N) dividing India into two heat zones","Only Torrid Zone"],ans:2,exp:"India spans both heat zones: (1) TORRID ZONE: the southern part of India (below 23.5 N) including most of Tamil Nadu, Kerala, Karnataka, Andhra Pradesh, Maharashtra, Gujarat's southern parts — total about half of India; (2) NORTH TEMPERATE ZONE: the northern part above 23.5 N including most of UP, Rajasthan, Punjab, Himachal Pradesh, J&K, Ladakh, Uttarakhand.",sec:"Grid and Concepts"},
{q:"Two places A and B are on the same latitude but different longitudes. What can you say?",opts:["They are at the same time zone","They have the same distance from both poles","They are at the same distance from the Equator but at different east-west positions","They have the same climate"],ans:2,exp:"Places on the same latitude are at the SAME DISTANCE from the Equator (same north-south position) but at different east-west positions. They have the same latitudinal angle but different longitudes. They may have similar climate zones (both in the same heat zone) but different local times and actual climates.",sec:"Grid and Concepts"},
{q:"Two places A and B are on the same longitude but different latitudes. What can you say?",opts:["They have the same local time","They are at the same distance from the Equator","They are on the same meridian — they have the SAME LOCAL TIME but are at different north-south distances from the Equator","They are in the same time zone"],ans:2,exp:"Places on the same meridian (same longitude) have the SAME LOCAL TIME because the Sun crosses their meridian at the same moment. However, they are at different distances from the Equator. They may have very different climates despite sharing the same local time. Example: London (0 E, 51 N) and Accra, Ghana (0 E, 5 N) share the Prime Meridian.",sec:"Grid and Concepts"},
{q:"The shape of the Earth affects distances between meridians. At 60 degrees latitude, the distance between two meridians is approximately:",opts:["111 km (same as equator)","55.5 km (half of equatorial distance, since cos 60 = 0.5)","88 km","33 km"],ans:1,exp:"Distance between meridians = 111 x cos(latitude) km. At 60 degrees: 111 x cos(60) = 111 x 0.5 = 55.5 km. At 45 degrees: 111 x 0.707 = about 78 km. At 30 degrees: 111 x 0.866 = about 96 km. At 90 degrees (poles): 111 x 0 = 0 km (all meridians meet). This shows why maps get distorted at higher latitudes.",sec:"Grid and Concepts"},
{q:"IST (Indian Standard Time) was adopted for the whole of India mainly for:",opts:["Following the British Greenwich standard","Scientific accuracy in astronomy","Uniform coordination of the Indian Railway and telegraph systems — adopted in 1906","Religious reasons — India follows one dharma so one time"],ans:2,exp:"IST was adopted in 1906 during the British era primarily for the coordination of Indian RAILWAY schedules across the subcontinent. Before this, different cities used their own local solar times (Bombay was about 39 minutes behind Calcutta in local time). Railway coordination required a single standard time. After independence, India retained IST.",sec:"Grid and Concepts"},
{q:"The Equator passes through which Indian ocean?",opts:["Bay of Bengal","Arabian Sea","INDIAN OCEAN — the Equator passes through the Indian Ocean south of India, between Africa and Indonesia","Pacific Ocean only"],ans:2,exp:"The Equator (0 degrees) passes through the Indian Ocean, south of India. India itself lies entirely north of the Equator (8 N to 37 N). The Equator also passes through the Atlantic Ocean and Pacific Ocean. In Asia, the Equator passes through the Maldives (just south), Indonesia, and the surrounding seas.",sec:"Grid and Concepts"},
{q:"What is the local time at 90 degrees E when it is 12 noon at the Prime Meridian (0 degrees)?",opts:["6:00 AM","9:00 AM","12:00 noon (same)","6:00 PM"],ans:3,exp:"90 E is 90/15 = 6 hours ahead of Greenwich. So 12:00 noon + 6 hours = 6:00 PM at 90 E. Kolkata is at approximately 88 E, so its local time is slightly less — about 5 hours 52 minutes ahead. But Kolkata uses IST (5 hours 30 min ahead), creating a small difference between local solar time and official time.",sec:"Grid and Concepts"},
{q:"The word 'MERIDIAN' comes from Latin meaning:",opts:["Of the morning","Of the sea","MIDDAY — because the Sun crosses a meridian at solar noon (midday). This is also why AM means Ante Meridiem (before noon) and PM means Post Meridiem (after noon)","Of the evening"],ans:2,exp:"Meridian comes from Latin Meridianus meaning of midday. The Sun crosses any given meridian at solar noon (the highest point in the sky that day). AM = Ante Meridiem (before the Sun crosses the meridian) and PM = Post Meridiem (after). This is why the word meridian is used for lines of longitude — the Sun crosses them at noon.",sec:"Grid and Concepts"},
{q:"What happens to day length at the Equator throughout the year?",opts:["It varies greatly from 10 to 14 hours","Day is always longer than night","Day length is ALWAYS APPROXIMATELY 12 HOURS every day throughout the year","Day is always shorter than night"],ans:2,exp:"At the Equator (0 degrees), day and night are ALWAYS approximately 12 hours each throughout the year. This is because the Equator is always equally divided by the circle of illumination regardless of Earth's position in its orbit. There is virtually no seasonal variation in day length at the Equator.",sec:"Grid and Concepts"},
{q:"What is the significance of the latitude 23.5 degrees N?",opts:["It is the boundary between Temperate and Frigid Zones","It is called the Tropic of Cancer — the northernmost latitude where the Sun can be directly overhead at noon (on June 21)","It marks the Arctic Circle","It is India's Standard Meridian expressed in latitude"],ans:1,exp:"23.5 N = Tropic of Cancer. It marks the northernmost point where the Sun is ever directly overhead at solar noon (June 21, Summer Solstice). This is because Earth's axial tilt is 23.5 degrees. Above this latitude, the Sun is never directly overhead. It also marks the northern boundary of the Torrid Zone.",sec:"Grid and Concepts"},
{q:"Why do ships and aircraft prefer Great Circle routes?",opts:["Great Circle routes are safer (avoid storms)","Great Circle routes pass over land only","Great Circle routes represent the SHORTEST distance between two points on the spherical surface of Earth","Great Circle routes use tailwinds"],ans:2,exp:"Great Circle routes are the SHORTEST path between two points on Earth's curved surface. On a flat map (Mercator projection), Great Circle routes look curved, but they are actually shorter on the globe. This is why a flight from India to USA flies over Central Asia and the Arctic — it looks longer on a flat map but is shorter on the actual globe.",sec:"Grid and Concepts"},
{q:"India's longitudinal extent from east to west (about 30 degrees) means that the sunrise in Arunachal Pradesh happens how much earlier than in Gujarat?",opts:["About 30 minutes earlier","About 1 hour earlier","About 2 hours earlier (30 degrees x 4 minutes per degree = 120 minutes)","About 3 hours earlier"],ans:2,exp:"India spans about 30 degrees of longitude. Each degree = 4 minutes of time difference. So 30 x 4 = 120 minutes = 2 hours. Sunrise occurs about 2 hours earlier in Arunachal Pradesh (easternmost) than in Gujarat (westernmost). Despite this, all of India uses the same IST clock time.",sec:"Grid and Concepts"},
{q:"Which of these statements about the International Date Line is CORRECT?",opts:["The IDL is a straight line exactly at 180 degrees","The IDL deviates from 180 degrees to avoid splitting countries and island groups across two different dates","The IDL passes through India","The IDL is the same as the Prime Meridian"],ans:1,exp:"The IDL is NOT a straight line. It deviates from 180 degrees to keep countries and island groups on one calendar date. Major deviations: bends east around Russia's Chukotka, bends west around Kiribati (which moved the line in 1995 to keep all its islands on the same date), and around Fiji, Tonga, and Samoa.",sec:"Grid and Concepts"},
{q:"The North Pole is located at:",opts:["0 degrees latitude, 0 degrees longitude","90 degrees N — all longitudes meet here so longitude is meaningless at the pole","66.5 degrees N, 90 degrees E","90 degrees N, 180 degrees E"],ans:1,exp:"The North Pole is at 90 degrees N latitude. At the North Pole, ALL longitudes (meridians) converge at a single point, so longitude becomes meaningless there. Every direction from the North Pole is south. The North Pole is in the Arctic Ocean (covered by sea ice) — there is no land directly under the pole.",sec:"Grid and Concepts"},
{q:"Which of the following is INCORRECT about lines of latitude?",opts:["They are also called parallels","They run in the east-west direction","They measure north-south angular distance from the Equator","THEY INCREASE IN LENGTH AS YOU MOVE TOWARD THE POLES — this is incorrect; parallels DECREASE in circumference toward the poles"],ans:3,exp:"Statement D is INCORRECT. Parallels DECREASE in circumference as you move from the Equator (longest: ~40,075 km) toward the poles (where circumference = 0). The Equator is the largest parallel. A parallel at 60 N or S has about half the circumference of the Equator. All other statements about latitudes are correct.",sec:"Grid and Concepts"},
{q:"The latitude of a place in the Southern Hemisphere is written as:",opts:["With a positive number (e.g., 25 degrees)","With the letter N after the number","With the letter S after the number (e.g., 25 degrees S) or as a negative number (e.g., -25 degrees)","With the letter W after the number"],ans:2,exp:"Southern latitudes are written with S (South) after the degrees, e.g., 25 S or -25 degrees. Northern latitudes use N, e.g., 25 N or +25 degrees. Similarly, eastern longitudes use E (e.g., 77 E or +77) and western longitudes use W (e.g., 75 W or -75). Sydney, Australia is at approximately 33.9 S, 151.2 E.",sec:"Grid and Concepts"},
{q:"What type of map projection preserves the shape of countries but distorts their size at higher latitudes?",opts:["Equal-area projection","MERCATOR PROJECTION — widely used for navigation; preserves direction and shape (conformal) but greatly enlarges areas near the poles; Greenland appears as large as Africa though Africa is 14 times bigger","Conical projection","Azimuthal projection"],ans:1,exp:"The Mercator Projection (Gerardus Mercator, 1569) preserves shape and direction (conformal projection) — useful for navigation as compass bearings are straight lines. However, it greatly distorts SIZE at higher latitudes. Greenland looks similar in size to Africa on Mercator maps, but Africa is about 14 times larger. Parallels and meridians appear as straight lines on Mercator maps.",sec:"Grid and Concepts"},
{q:"Which statement correctly summarizes the difference between Latitude and Longitude?",opts:["Latitude measures east-west position; Longitude measures north-south position","LATITUDE measures north-south angular distance from the Equator (0 to 90 N or S); LONGITUDE measures east-west angular distance from the Prime Meridian (0 to 180 E or W)","Both measure the same thing in different ways","Latitude is used for maps; Longitude is used for time only"],ans:1,exp:"LATITUDE = north-south measurement from the Equator (0 degrees); ranges 0 to 90 N or S; lines are called Parallels; used to determine climate zones and heat zones. LONGITUDE = east-west measurement from Prime Meridian (0 degrees); ranges 0 to 180 E or W; lines are called Meridians; used to calculate local time and time zones. Together they form the geographic coordinate system.",sec:"Grid and Concepts"}
];

const qSt=new Array(100).fill(0);
let cur=0,cor=0,wrn=0,xp=0,str=0,bStr=0,done=false;
const L=["A","B","C","D"];
const SC={"Latitude Basics":"#3b82f6","Longitude Basics":"#8b5cf6","Heat Zones":"#ef4444","Time and IST":"#f59e0b","India Lat Long":"#f97316","Grid and Concepts":"#10b981"};
const RM=["She is more precise than GPS coordinates 😍🎯","That answer was right on the prime meridian 🗺️🔥","Geographers worldwide are bowing down 🌍😍","You plotted that answer perfectly queen 📍👑","Zero degrees of doubt in that answer ✨😍","Miss Geography Queen has entered the chat 🌍💅","SSC CGL geography section fears you 💅🗺️","That brain operates across all time zones simultaneously 🌐💕","She knows her meridians and she knows them WELL 😍🌍","The Prime Meridian approves of this answer 😍✨","Perfect coordinates queen 📍😍","That is the energy that cracks SSC CGL Geography 🎯💕","She is not studying geography, geography is studying HER 😤🔥","Accuracy level: off the charts and the chart is a world map 🗺️😍","From the equator to the poles — all correct, all queen 💕✨","That answer made NCERT proud 📚😍","Straight A student energy confirmed 🏆✨","The Tropic of Cancer felt that correct answer 🌞💕","Even Mirzapur (IST meridian) is cheering for you 🎉😍","Zero latitude for error in that answer 💅🔥"];
const WM=["Babe even the equator has better direction than that 😭💀","Girl that answer just got lost between meridians 💀","Your latitude for getting this right? Negative 💀😂","The Prime Meridian called — it is disappointed 📞💀","That missed the standard meridian by 180 degrees 😭","Even the IDL makes more sense than that answer 💀😂","Wrong hemisphere bestie 💀✨","Babe that answer is so wrong it has its own time zone 💀","Your NCERT Geography is sobbing 📚😭","That is giving I-confused-latitude-with-longitude energy 😭","Darling no 😭 even the Tropic of Cancer is disappointed","Wrong babe but your confidence is as high as 90 degrees N 💀😂","The Samiti would vote against that answer 😂","Even Mirzapur knows the answer and it is a city 💀","Girl no 💀 reread that NCERT chapter tonight","That answer crossed the IDL and still came out wrong 💀😂","Wrong answer with the confidence of a Samrat — impressive but incorrect 😂","Even the midnight sun is confused by that answer 💀","That is giving never-opened-Class-11-Geography energy 😂📚","Your answer just went past the poles with no correction 💀"];

function buildNav(){const g=document.getElementById("ngrid");g.innerHTML="";for(let i=0;i<100;i++){const b=document.createElement("button");b.className="nqb"+(i===cur?" iscur":qSt[i]===1?" isok":qSt[i]===2?" isbad":"");b.id="nq"+i;b.textContent=i+1;b.onclick=()=>{jumpQ(i);closeNav()};g.appendChild(b);}}
function updateNav(){for(let i=0;i<100;i++){const b=document.getElementById("nq"+i);if(!b)continue;b.className="nqb"+(i===cur?" iscur":qSt[i]===1?" isok":qSt[i]===2?" isbad":"");}}
function openNav(){buildNav();document.getElementById("navpanel").classList.add("on");document.getElementById("overlay").classList.add("on")}
function closeNav(){document.getElementById("navpanel").classList.remove("on");document.getElementById("overlay").classList.remove("on")}
function render(){
  if(cur>=Q.length){showResult();return;}
  const q=Q[cur];done=false;
  const col=q.sec?SC[q.sec]:"#7c3aed";
  document.getElementById("qcard").style.setProperty("--sc",col);
  document.getElementById("qNL").textContent="Q"+(cur+1)+" of 100";
  const st=document.getElementById("stag");st.textContent=(q.sec||"LAT & LONG").toUpperCase();
  st.style.cssText="font-size:.63rem;font-weight:700;padding:2px 8px;border-radius:5px;letter-spacing:.4px;background:"+col+"20;color:"+col+";border:1px solid "+col+"40";
  document.getElementById("qT").textContent=q.q;
  document.getElementById("pb").style.width=cur+"%";
  document.getElementById("qC").textContent="Q "+(cur+1)+" / 100";
  const oc=document.getElementById("oc");oc.innerHTML="";
  q.opts.forEach((o,i)=>{const b=document.createElement("button");b.className="opt";b.innerHTML='<span class="oltr">'+L[i]+'</span><span>'+o+'</span>';b.onclick=()=>pick(i,b);oc.appendChild(b);});
  document.getElementById("fbc").className="fb";document.getElementById("nb").className="nxt";
  document.getElementById("fba").style.display="none";document.getElementById("fbv").textContent="";
  updateMeta();updateNav();
}
function pick(sel,btn){
  if(done)return;done=true;const q=Q[cur];
  document.querySelectorAll(".opt").forEach(b=>b.disabled=true);
  document.querySelectorAll(".opt")[q.ans].classList.add("correct");
  const fbc=document.getElementById("fbc"),fbt=document.getElementById("fbt"),fbv=document.getElementById("fbv"),fba=document.getElementById("fba"),fbe=document.getElementById("fbe");
  fbc.classList.add("on");
  if(sel===q.ans){
    cor++;str++;if(str>bStr)bStr=str;const bon=Math.min(str*4,50);xp+=10+bon;qSt[cur]=1;
    btn.classList.add("correct");fbc.className="fb on fc";fbt.className="fb-title c";fbt.textContent="Correct";
    const rm=RM[Math.floor(Math.random()*RM.length)];fbv.textContent=rm;fba.style.display="none";
    spawnConf();spawnHearts();toast(rm+" +"+(10+bon)+" XP");
  } else {
    wrn++;str=0;qSt[cur]=2;btn.classList.add("wrong");
    fbc.className="fb on fw";fbt.className="fb-title w";fbt.textContent="Incorrect";
    const wm=WM[Math.floor(Math.random()*WM.length)];fbv.textContent=wm;fba.style.display="block";
    fba.textContent="Correct: "+L[q.ans]+". "+q.opts[q.ans];toast(wm);
  }
  fbe.textContent=q.exp||"";document.getElementById("nb").classList.add("on");
  updateMeta();updateNav();
}
function next(){cur++;const c=document.getElementById("qcard");c.style.animation="none";c.offsetHeight;c.style.animation="";render();}
function jumpQ(i){cur=i;done=false;render()}
function updateMeta(){document.getElementById("cC").textContent=cor;document.getElementById("wC").textContent=wrn;document.getElementById("xpV").textContent=xp;document.getElementById("strV").textContent=str;const t=cor+wrn;document.getElementById("accV").textContent=t?Math.round(cor/t*100)+"%":"--";}
function spawnConf(){const cols=["#3b82f6","#a78bfa","#10b981","#f59e0b","#f472b6","#fff","#ef4444"];for(let i=0;i<40;i++){const el=document.createElement("div");el.className="cf";const s=4+Math.random()*9,d=1.1+Math.random()*1.6;el.style.cssText="left:"+Math.random()*100+"vw;width:"+s+"px;height:"+s+"px;background:"+cols[Math.floor(Math.random()*cols.length)]+";border-radius:"+(Math.random()>.5?"50%":"2px")+";animation-duration:"+d+"s;animation-delay:"+Math.random()*.5+"s";document.body.appendChild(el);setTimeout(()=>el.remove(),(d+.6)*1000);}}
function spawnHearts(){const em=["💕","🌍","🗺️","📍","✨","🌐","💫","🛰️","💖","🧭"];for(let i=0;i<6;i++){const el=document.createElement("div");el.className="heart";el.textContent=em[Math.floor(Math.random()*em.length)];const dur=.8+Math.random()*.8;el.style.cssText="left:"+(10+Math.random()*80)+"vw;top:"+(20+Math.random()*40)+"vh;animation-duration:"+dur+"s;animation-delay:"+Math.random()*.3+"s";document.body.appendChild(el);setTimeout(()=>el.remove(),(dur+.4)*1000);}}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("on");setTimeout(()=>t.classList.remove("on"),2400);}
function showResult(){
  document.getElementById("qa").style.display="none";document.getElementById("rs").classList.add("on");
  const pct=Math.round(cor/100*100),sk=100-cor-wrn;
  document.getElementById("rsc").textContent=cor+"/100";
  ["rc","rw","ra","rx","rst2","rsk"].forEach((id,i)=>{document.getElementById(id).textContent=[cor,wrn,pct+"%",xp,bStr,sk][i];});
  let tr,ti,msg;
  if(pct>=90){tr="🌍";ti="Geography Queen";msg="You just aced every single NCERT Lat-Long concept. SSC CGL Geography is officially scared of you. Future IAS/IFS officer energy confirmed! 💅🔥";}
  else if(pct>=75){tr="🏆";ti="She Mapped That!";msg="Brilliant! Strong command over all the basics. Review the few you missed and you will be completely untouchable in SSC CGL Geography 💪✨";}
  else if(pct>=60){tr="📍";ti="Good Navigation!";msg="Solid score! You know the core concepts. Focus on: IST = UTC+5:30, 8 states of Tropic of Cancer, 5 major parallels, and 15 degrees = 1 hour. Come back stronger 📚💕";}
  else if(pct>=40){tr="🧭";ti="Getting Oriented!";msg="You are finding your direction. Review NCERT Class 6 and 11 Geography chapters on Globe and Latitudes-Longitudes. Note the key values and come back 🌟";}
  else{tr="💡";ti="Just Starting!";msg="Every topper starts somewhere. Read the NCERT chapter carefully, note: Equator=0, Tropics=23.5, Polar Circles=66.5, IST=UTC+5:30, Standard Meridian=82.5E through Mirzapur 🚀💕";}
  document.getElementById("rtr").textContent=tr;document.getElementById("rti").textContent=ti;document.getElementById("rm").textContent=msg;
  if(pct>=75){spawnConf();spawnHearts();}
}
function restart(){cur=0;cor=0;wrn=0;xp=0;str=0;bStr=0;done=false;qSt.fill(0);document.getElementById("qa").style.display="block";document.getElementById("rs").classList.remove("on");render();updateMeta();}
render();
